/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('images').del()
  await knex('images').insert([
    {
      id: 313,
      filename: '44.jpeg',
      date: '2017-10-22',
      title: 'Snoozles ...',
      description: null,
      tags: 'species/human name/adam with/snoozles',
      starred: null,
      views: 0,
    },
    {
      id: 296,
      filename: '29.jpeg',
      date: '2015-03-14',
      title: null,
      description: null,
      tags: 'with/smiles species/human name/adam with/food',
      starred: null,
      views: 0,
    },
    {
      id: 274,
      filename: '125.jpeg',
      date: '2022-06-09',
      title: 'Adam <3s parrots',
      description: null,
      tags: 'name/adam species/human species/parrot',
      starred: null,
      views: 0,
    },
    {
      id: 310,
      filename: '41.jpeg',
      date: '2017-05-12',
      title: 'Buddies',
      description: null,
      tags: 'species/cat species/human name/adam name/andre',
      starred: null,
      views: 4,
    },
    {
      id: 361,
      filename: '88.jpeg',
      date: '2022-06-09',
      title: null,
      description: null,
      tags: 'with/car name/audrey species/human name/adam species/dog name/dio',
      starred: null,
      views: 0,
    },
    {
      id: 367,
      filename: '93.jpeg',
      date: '2022-06-09',
      title: 'Setting up garden beds',
      description: null,
      tags: 'name/audrey with/garden species/human with/wheelbarrow species/dog name/adam',
      starred: null,
      views: 0,
    },
    {
      id: 342,
      filename: '70.jpeg',
      date: '2022-06-02',
      title: 'Morning coffee run',
      description: null,
      tags: 'with/smiles species/human name/adam species/dog with/car',
      starred: null,
      views: 0,
    },
    {
      id: 369,
      filename: '95.jpeg',
      date: '2022-06-09',
      title: 'Cuddles',
      description: null,
      tags: 'with/smiles species/human name/adam species/dog name/dio',
      starred: null,
      views: 0,
    },
    {
      id: 254,
      filename: '107.jpeg',
      date: '2022-06-09',
      title: 'Hungry',
      description: null,
      tags: 'with/derp name/audrey species/human name/adam species/dog with/teeth',
      starred: null,
      views: 0,
    },
    {
      id: 271,
      filename: '122.jpeg',
      date: '2022-06-09',
      title: 'Emily <3 roses',
      description: null,
      tags: 'name/emily with/rose species/human name/adam species/goat',
      starred: null,
      views: 0,
    },
    {
      id: 294,
      filename: '27.jpeg',
      date: '2014-07-03',
      title: 'Kiwi Gothic',
      description: null,
      tags: 'with/phone species/human name/adam name/tink',
      starred: null,
      views: 3,
    },
    {
      id: 323,
      filename: '53.jpeg',
      date: '2019-11-25',
      title: 'Chanelling Ned',
      description: null,
      tags: 'species/human name/adam name/tink with/derp',
      starred: null,
      views: 0,
    },
  ])
}
